language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO_URL=postgres://postgres:@localhost:5432/travisci
  - DJANGO_VERSION=1.10.5

before_install:
  - export DJANGO_SETTINGS_MODULE=quickstart.settings
  - export PYTHONPATH=$HOME/builds/synnick/django-playground
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create database travisci;' -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test
