version: '2'
services:
  db:
    container_name: db
    image: postgres
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:@db:5432/postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
